# Generated by Django 3.2.8 on 2021-11-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.CharField(max_length=10)),
                ('group', models.CharField(max_length=20)),
                ('lot', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=15)),
                ('remaining', models.FloatField()),
                ('unit', models.CharField(max_length=8)),
            ],
        ),
    ]
